### PR TITLE
tag: Cleanup regex, put tags under AfD notices, fix prod regex, put under salt and endorsed prod

### LINKED ISSUE #237: Request: put maintenance tags below deletion notices
Would it be possible for Twinkle to put new maintenance tags below CSD/PROD/AFD tags?  It would prevent me from having to fix edits like this: https://en.wikipedia.org/w/index.php?title=Bell_Integrator&diff=616390399&oldid=616389887

### PR DESCRIPTION
**Pull request by Amorymeltzer**
1st commit: Continues on #541, closes #237.  Makes regex far more readable per @siddharthvp.  Put tags under AfD notices and actually work for PROD now, as #541 didn't really account for the multi-line input from subst-ing.

2nd commit: Puts tags under `{{salt}}` and `{{endorsed prod}}`

### CODE REVIEW

File: modules/friendlytag.js [hunk 1]
```diff
@@ -1276,12 +1276,38 @@ Twinkle.tag.callbacks = {
...
+					')\\d*\\s*' +
+					// template parameters
+					'(\\|(?:\\{\\{[^{}]*\\}\\}|[^{}])*)?' +
+					// end template format
+					'\\}\\})+' +
+					// end capture
+					'(?:\\s*\\n)?)' +
+					// trailing whitespace
+					'\\s*)?',
+					'i'), "$1" + tagText
```
Comment (siddharthvp) [inline modules/friendlytag.js]: L1309 Should be outdented by 1 tab level. Thanks for including me as co-author on this.

Comment (Amorymeltzer) [reply modules/friendlytag.js]:
```suggestion
						'i'), "$1" + tagText
```

**Comment by Amorymeltzer** [comment]
@siddharthvp No rush, but I'll be doing a big on-wiki update later this week.  I was gonna hold this to wait on #485 as you've already poured enough sweat and blood into that PR, but this does include a few fixes (namely fixing the prod regex) that would be helpful on-wiki.  Would it cause you too much agita if I merged this?  Seriously, not pushing you, take your time; I feel bad for sending you more merge conflicts!

**Comment by siddharthvp** [comment]
@Amorymeltzer Sorry to complicate this further, but on 2nd/3rd nomination, TW adds {{AfDM}} instead of {{Article for deletion/dated}}. What's more, even the html comments are a bit different. Compare [1](https://en.wikipedia.org/w/index.php?title=Blu-spec_CD&diff=897644002&oldid=875069477) with [2](https://en.wikipedia.org/w/index.php?title=The_Leading_Hotels_of_the_World&diff=next&oldid=898724798).

**Comment by siddharthvp** [comment]
never mind, figured out the fix myself, #642.

**Comment by Amorymeltzer** [comment]
I'm pretty sure I had that on my todo list for this and it slipped out in the shuffle, good catch!
