### PR TITLE
tag: fix bug when processing items with type=div

### LINKED ISSUE #624: {{R from alternative language}} tag broken
Currently, when I try to add {{R from alternative language}} tags to redirects Twinkle silently fails. It doesn't appear to matter whether I enter language codes or fill in other parameters. I am still able to use other tags, even after attempting to add the {{R from alternative language tag}}

System specs: Mac OS 10.14.4, bug is present on  the latest versions of Safari and Firefox.

### PR DESCRIPTION
**Pull request by Amorymeltzer**
Closes #624.  {{R from alternative name}} has a div element, and the processing schema introduced in #487 dies on it

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
@siddharthvp I'm sure you can cook up a smarter way to deal with this but I'm tired and heading to bed in a moment so this should suffice for the time being.

File: modules/friendlytag.js [hunk 1]
```diff
@@ -1541,7 +1541,7 @@ Twinkle.tag.callback.evaluate = function friendlytagCallbackEvaluate(e) {
 	// name attribute as 'articleTags.' + name of the subgroup element
 
 	var name_prefix = Twinkle.tag.mode + 'Tags.';
-	$(form).find("[name^='" + name_prefix + "']").each(function(idx,el) {
+	$(form).find("[name^='" + name_prefix + "']:not(div)").each(function(idx,el) {
```
Comment (siddharthvp) [inline modules/friendlytag.js]:
```suggestion
	$(form).find("input[name^='" + name_prefix + "']").each(function(idx,el) {
```
Slightly cleaner.
