### PR TITLE
xfd: add delsort to afd

### LINKED ISSUE #143: Add deletion sorting
https://en.wikipedia.org/wiki/User:John_Vandenberg/Deletion_sorting_tool required TW to work but has since started not working and, according to John Vandenberg, needs to be completely rewritten. Instead of having a standalone deletion sorting tool that requires TW it would be nice if deletion sorting was incorporated into TW.

### PR DESCRIPTION
**Pull request by siddharthvp**
Allow listing of the discussion on deletion sorting pages while creating an AFD. Closes #143. While there may be no need for Twinkle to provide a standalone delsort tool, it would be probably helpful to have one within xfd module, allowing afd nominators to sort their afds while creating it. 

This makes use of the `jquery.chosen` module/library, which I have loaded using `mw.loader.using`. Do we have to add it to the list of dependencies or do something funny like that? I'd think not. @MusikAnimal ? 

This is inspired from Enterprisey's [delsort tool](https://en.wikipedia.org/wiki/User:Enterprisey/delsort), from where the the list of delsort pages has been copied from.

### CODE REVIEW

File: modules/twinklexfd.js [hunk 1]
```diff
@@ -740,6 +809,13 @@ Twinkle.xfd.callbacks = {
 			}
 			usertalkpage.setFollowRedirect(true);
 			usertalkpage.append();
+		},
+		delsortListing: function(pageobj) {
+			var discussionPage = pageobj.getCallbackParameters().discussionPage;
+			var text = pageobj.getPageText().replace("directly below this line -->", "directly below this line -->\n{{" + discussionPage + "}}");
+			pageobj.setPageText(text);
+			pageobj.setEditSummary('Listing [[:' + discussionPage +']].' + Twinkle.getPref('summaryAd'));
+			pageobj.save();
```
Comment (Amorymeltzer) [inline modules/twinklexfd.js]:
```suggestion
			pageobj.setCreateOption('nocreate');
			pageobj.save();
```

Just to be safe, eh?

File: modules/twinklexfd.js [hunk 2]
```diff
@@ -203,9 +203,61 @@ Twinkle.xfd.callback.change_category = function twinklexfdCallbackChangeCategory
...
+			var grp = delsort.append( { type: 'optgroup', label: grpname } );
+			list.forEach(function(item) {
+				grp.append( { type: 'option', label: item, value: item } );
+			});
+		});
+
 		appendReasonBox();
 		work_area = work_area.render();
 		old_area.parentNode.replaceChild( work_area, old_area );
+		mw.loader.using('jquery.chosen').then(function chosenInit() {
```
Comment (Amorymeltzer) [inline modules/twinklexfd.js]: Fairly certain this shouldn't be here, but rather it is dealt with at [MediaWiki:Gadgets-definition](https://en.wikipedia.org/wiki/MediaWiki:Gadgets-definition). 
 That is, this should be changed in the [readme](https://github.com/azatoth/twinkle/blob/master/README.md#updating-scripts-on-wikipedia), although this clearly isn't used by anything else at the moment.

**Comment by Amorymeltzer** [comment]
Left a couple comments, not a full review — would like to hear what @MusikAnimal thinks first.  Also cc @enterprisey.

@enterprisey How did you come up with that list, I'm sure that's not the full extent of possibilities?  If this does go forward, I think it'd be good for us to come up with a set criterion for inclusion/exclusion here.

**Comment by JJMC89** [comment]
> @enterprisey How did you come up with that list, I'm sure that's not the full extent of possibilities? If this does go forward, I think it'd be good for us to come up with a set criterion for inclusion/exclusion here.

It is based on [Wikipedia:WikiProject Deletion sorting/Compact](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Deletion_sorting/Compact). WP:DS/C is likely missing some pages, and the list in the script it is likely out of sync with WP:DS/C since I haven't been keeping up with it.

File: modules/twinklexfd.js (hunk 2 above)
Comment (siddharthvp) [reply modules/twinklexfd.js]: We don't need to load jquery.chosen unless the TW xfd module is opened and mode is set to AFD. I don't see the benefit in having it load on every page.

Comment (siddharthvp) [reply modules/twinklexfd.js]: BTW, jquery.chosen will look good on warn module too, for warning selection dropdown, as I have said elsewhere earlier.

**Comment by MusikAnimal** [comment]
Deletion sorting is one thing I've virtually no experience in... so I may not have much to offer here. That said, I don't see a lot of new code, so this seems like an acceptable addition that isn't too far out of scope. I would be weary of letting it grow into a large, full-on delsort module (should that be the concern), since it is a very niche area of the project.

**Comment by MusikAnimal** [comment]
Regarding `jquery.chosen`, it's certainly cleaner to specify this in the gadget definition, though I agree XfD is among the less popular modules. It will load very fast, and the client will cache it (so negligible difference in a single session), but it's still 10 KB of JavaScript for something that won't be used often.

Have we considered the native [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)? It may not look as pretty but it may work just as well here, and is safe for us to use in terms of browser compatibility.

**Comment by siddharthvp** [comment]
`datalist` allows user input that's not a part of the options in the dropdown. I don't think we want that here. Also it doesn't seem to support multiple inputs, which is necessary here. 

jquery.chosen is good in terms of browser compatibility: I've tested it in IE too. On mobile browsers, the chosen features don't work - the field fallbacks to the native multi-select, which still is usable. 

I don't have any strong preference regarding how we load it. Its used on several of Enterprisey's scripts and we could use it in the Warn module too, so maybe the 10kb JS won't be that unused if we put it in the gadget definition.

**Comment by Amorymeltzer** [comment]
I'd much prefer it in the definition, if only for cleanliness and consistency, but js does already take a noticeable time to load for some (although I think popups is far and away the worst offender?), so I'm sympathetic to the inline style.

That being said, we *could* use it for nearly everything with a longish dropdown, no?  I dunno if it's a good idea — at a minimum it clashes a bit with our non-ooui style — but it would avoid things like #491, where you first mentioned it, and might be appreciated in @MusikAnimal's `block` module. 🤔

**Comment by MusikAnimal** [comment]
Sounds fine to me!

File: modules/twinklexfd.js (hunk 2 above)
Comment (Amorymeltzer) [reply modules/twinklexfd.js]: Per comments below

File: modules/twinklexfd.js [hunk 3]
```diff
@@ -203,9 +203,61 @@ Twinkle.xfd.callback.change_category = function twinklexfdCallbackChangeCategory
...
+			"Geographic/Americas/USA": ["United States of America", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia (U.S. state)", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "Washington, D.C.", "West Virginia", "Wisconsin", "Wyoming"],
+			"Geographic/Unsorted": ["Islands"]
+		};
+
+		var delsort = work_area.append( {
+			type: 'select',
+			multiple: true,
+			name: 'delsort',
+			label: 'Choose deletion sorting pages to list in: '
```
Comment (Amorymeltzer) [inline modules/twinklexfd.js]: Awkward phrasing.  Maybe something like `Deletion sorting categories to list article in` or `Deletion categories to sort article into`?  I'd prefer `in which to sort article` but I think I'm likely alone there!  I also think it'd be a good idea to have a tooltip with some additional guidance, in particular around not going too crazy.  There's been some abuse lately, and a discussion is currently ongoing about this, so better to nip it in the bud.  Not sure if the below is best.

```suggestion
			label: 'Deletion categories to sort article into: ',
			tooltip: 'Only select a few specific categories that are meaningful and significant to the subject of the article.'
```

File: modules/twinklexfd.js (hunk 2 above)
Comment (Amorymeltzer) [inline modules/twinklexfd.js]:
```suggestion
		// TODO: Add to the gadget definition if used elsewhere
		mw.loader.using('jquery.chosen').then(function chosenInit() {
```

File: modules/twinklexfd.js [hunk 4]
```diff
@@ -520,6 +579,7 @@ Twinkle.xfd.callbacks = {
 		if (form.xfdtarget2) {
 			params.target2 = form.xfdtarget2.value;
 		}
+		params.delsort_cats = $(form.delsort).val();
```
Comment (Amorymeltzer) [inline modules/twinklexfd.js]: I know this will likely be dealt with in another of your pulls, but why the jquery here compared to the others?

File: modules/twinklexfd.js [hunk 5]
```diff
@@ -203,9 +203,61 @@ Twinkle.xfd.callback.change_category = function twinklexfdCallbackChangeCategory
...
+			});
+		});
+
 		appendReasonBox();
 		work_area = work_area.render();
 		old_area.parentNode.replaceChild( work_area, old_area );
+		mw.loader.using('jquery.chosen').then(function chosenInit() {
+			$(work_area).find('[name=delsort]')
+				.attr('data-placeholder', 'Select delsort pages')
+				.chosen({width: "100%"});
```
Comment (Amorymeltzer) [inline modules/twinklexfd.js]: CSS isn't my strong suit but I don't suppose there's any way to get this to start on the same line as the label, but then be at 100% when multiline?  I think it's either/or.

**Comment by Amorymeltzer** [comment]
One other thing I think would be good to commit here is what to include/exclude in the future.  I'm fine cribbing off @enterprisey and/or WP:DS/C, but we should definitely say so.

**Comment by enterprisey** [comment]
Looks good! I originally got it from DS/C, and then people would periodically tell me about new lists to add on my user talk page (or submit pull requests to my github repo).

File: modules/twinklexfd.js (hunk 4 above)
Comment (Amorymeltzer) [reply modules/twinklexfd.js]: I had thought this would be nullified by #597 but seems not.  Still think this should match the others.

Comment (siddharthvp) [reply modules/twinklexfd.js]: Can't do that, `value` property for a multi-select input gives only the first selected option rather than the list of all selected options, which we need.

Comment (Amorymeltzer) [reply modules/twinklexfd.js]: Indeed!

**Comment by Amorymeltzer** [comment]
@siddharthvp I know you're busy, but my changes are just comment-tweaks, so if you don't mind, I think I can handle that in the terminal and get this merged and pushed live today.

File: modules/twinklexfd.js (hunk 5 above)
Comment (siddharthvp) [reply modules/twinklexfd.js]: Don't really follow. Are u saying that the input box should be on the same line as the label? I don't think so since the label is kinda long, also if there are multiple delsorts, they'd take up space.

File: modules/twinklexfd.js (hunk 3 above)
Comment (siddharthvp) [reply modules/twinklexfd.js]: Made the label "Choose deletion sorting categories: ", as I think it'd be good to preserve the original phrasing "deletion sorting" somewhere, so that ppl know what exactly this is. 

Dont really agree with the tooltip. My reading of the consensus at [the discussion](https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Deletion_sorting#Is_there_such_a_thing_as_too_much_deletion_sorting?) is that generally AfDs may be put into as many delsorts as possible.

File: modules/twinklexfd.js (hunk 5 above)
Comment (Amorymeltzer) [reply modules/twinklexfd.js]: I don't think it's possible, but what I *really* want is for it to be on the same line, but then when it would overflow, the input would be on it's own line.  Not something I intended for you to fix, just wishin'

File: modules/twinklexfd.js (hunk 3 above)
Comment (Amorymeltzer) [reply modules/twinklexfd.js]: 👍 on the first point.  As for that discussion, I don't think there was much of a consensus reached either way, but as this will be new behavior for editors and most do not DELSORT after nomination, some level of how to chose might be appreciated.

Maybe if I tone down my initial suggestion to something like
`tooltip: 'Select a few categories that are relevant to the subject of the article.'`

If you object to the "a few" that can be removed.

Comment (siddharthvp) [reply modules/twinklexfd.js]: Done.

File: modules/twinklexfd.js (hunk 5 above)
Comment (siddharthvp) [reply modules/twinklexfd.js]: Not possible it seems. But even if it was, I'd say such "jumping" elements are poor user interfaces.
